export const data = [
  {
    id: crypto.randomUUID(),
    nav_name: "About Me",
    hed: "Ben Scott",
    bg: "video",
    // asset: "ast.mp4",
    textColor: "black",
  },
  {
    id: crypto.randomUUID(),
    nav_name: "Near-Earth Asteroids",
    hed: "These are the five most dangerous asteroids",
    link: "https://www.nationalgeographic.com/premium/graphics/five-asteroids-could-hit-earth",
    bg: "video",
    asset: "ast.mp4",
    textColor: "white",
    bts: true,
  },
  {
    id: crypto.randomUUID(),
    nav_name: "Seashell Builder",
    hed: "Build your very own seashell",
    link: "https://www.nationalgeographic.com/science/graphics/design-your-own-shell",
    bg: "video",
    asset: "shells.mp4",
    textColor: "#3c6262",
    bts: true,
  },
  {
    id: crypto.randomUUID(),
    nav_name: "Massive Ant Mound",
    hed: "Watch this massive ant colony survive a year of challenges",
    link: "https://www.nationalgeographic.com/animals/graphics/explore-redwood-ants-colony-survival",
    bg: "video",
    asset: "ants.mp4",
    textColor: "white",
    bts: true,
    navBg: true,
  },
  {
    id: crypto.randomUUID(),
    nav_name: "Mummy Workshop",
    hed: "Step inside this ancient mummification workshop",
    link: "https://www.nationalgeographic.com/premium/graphics/egypt-mummy-saqqara-excavation-golden-age-feature",
    bg: "image",
    asset: "mummy.png",
    textColor: "white",
    bgColor: "#8f7d60",
    bts: true,
  },
  {
    id: crypto.randomUUID(),
    nav_name: "Camp Century",
    hed: "Explore Camp Century, a Cold War-era military base buried in the Greeland icecap",
    link: "https://www.nationalgeographic.com/history/graphics/explore-camp-century-history-impact",
    bg: "image",
    asset: "poy.png",
    textColor: "white",
    navBg: true,
  },
  {
    id: crypto.randomUUID(),
    nav_name: "Artemis 1",
    hed: "A visual guide of NASA's plan for returning to the moon",
    link: "https://www.nationalgeographic.com/magazine/graphics/a-visual-guide-of-nasas-plan-to-get-back-to-the-moon",
    bg: "image",
    asset: "art2.png",
    textColor: "white",
  },
  {
    id: crypto.randomUUID(),
    nav_name: "Deer Antlers",
    hed: "Why do deer shed their antlers annually?",
    link: "https://www.nationalgeographic.com/animals/graphics/deer-antlers-shed-regrow",
    bg: "image",
    asset: "poy.png",
    textColor: "white",
  },
  {
    id: crypto.randomUUID(),
    nav_name: "Fertility Rate",
    hed: "Smaller families, starting Later: the drop of fertility rates in the US",
    link: "https://www.nationalgeographic.com/premium/graphics/us-fertility-rate-older-and-lower",
    bg: "image",
    asset: "fertility.png",
    textColor: "black",
  },
];
